name: finallapp
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.15.0
  firebase_auth_web: ^5.8.14
  cloud_firestore: ^4.14.0
  google_sign_in: ^5.3.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^0.13.6
  audioplayers: ^5.2.1
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  generate: true  # ✅ Enable localization code generation

  assets:
    - lib/assets/user.png
    - lib/assets/alarm.mp3


