name: finallapp
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  image_picker: ^1.0.4
  firebase_core: ^2.27.0
  firebase_auth: ^4.15.0
  firebase_auth_web: ^5.8.14
  cloud_firestore: ^4.14.0
  google_sign_in: ^5.3.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  audioplayers: ^5.2.1
  flutter_animate: ^4.2.0  # ← Add this line
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0  # надёжнее определяет “есть ли реальный интернет”
  hive: ^2.2.3
  hive_flutter: ^1.1.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/user.png
    - assets/user_profile.json

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6